version: '3.7'
services:
  delbur-nginx:
    image: delbur-nginx:${IMAGE_TAG}
    container_name: delbur-app-nginx
    ports:
      - ${TEST_WEB_PORT}:80
    volumes:
      - .:/app
    depends_on:
      - delbur-php-fpm
      - delbur-redis

  delbur-redis:
    image: redis:3.2.10-alpine
    container_name: delbur-app-redis
    ports:
      - 63791:6379

  delbur-mariadb:
    image: mariadb:10.1.32
    container_name: delbur-app-mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${TEST_DB_PATH}:/var/lib/mysql
      - ./docker/development/mariadb/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 33061:3306

  delbur-php-fpm:
    image: delbur-php-fpm:${IMAGE_TAG}
    container_name: delbur-app-php-fpm
    volumes:
      - .:/app

  delbur-php-cli:
    image: delbur-php-cli:${IMAGE_TAG}
    container_name: delbur-app-php-cli
    volumes:
      - .:/app

  delbur-node-cli:
    image: node:12.18.2-alpine
    container_name: delbur-app-node-cli
    volumes:
      - .:/app
    working_dir: /app
  
  delbur-sphinx:
    image: jc21/sphinxsearch
    container_name: delbur-app-sphinx
    ports:
      - 9306:9306
      - 9312:9312
    volumes:
      - "./docker/development/sphinx/sphinx.conf:/etc/sphinx/sphinx.conf"
      - "./docker/development/sphinx/data:/var/lib/sphinx"
    depends_on:
      - delbur-mariadb
networks:
  default:
    name: delbur-dev_default